import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {generateX25519KeyPair,decryptRequest,encryptRequest,encryptResult,PROTOCOL} from '../app/src/control-crypto.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const PY=ROOT+'/tools/chatgpt_control.py',NODE=ROOT+'/app/bin/navish-github-control.mjs';
for(const [name,cmd,pre] of [['Node',process.execPath,[NODE]],['Python','python3',[PY]]]){
 test(name+' prepare never overwrites the caller response key',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'navish-sender-'));try{const kp=generateX25519KeyPair(),dev=d+'/device.json',out=d+'/command.json',key=d+'/key.pem';fs.writeFileSync(dev,JSON.stringify({protocol:PROTOCOL,controllerId:'test',publicKeyPem:kp.publicKeyPem}));const args=[...pre,'prepare','--device-json',dev,'--target','local','--tool','get_config','--command-id','prepared','--out',out,'--response-key',key];const env={...process.env,HOME:d,NAVISH_CONFIG_DIR:d+'/config',NAVISH_STATE_DIR:d+'/state',NAVISH_DATA_DIR:d+'/data'};
 let r=spawnSync(cmd,args,{env,encoding:'utf8'});assert.equal(r.status,0,r.stderr);const first=fs.readFileSync(key),envelope=fs.readFileSync(out);r=spawnSync(cmd,args,{env,encoding:'utf8'});assert.notEqual(r.status,0);assert.deepEqual(fs.readFileSync(key),first);assert.deepEqual(fs.readFileSync(out),envelope);assert.equal(fs.statSync(key).mode&0o777,0o600);assert.equal(decryptRequest({devicePrivateKeyPem:kp.privateKeyPem,envelope:JSON.parse(envelope)}).tool,'get_config');}finally{fs.rmSync(d,{recursive:true,force:true})}});
 test(name+' prepare refuses a partial preexisting response-key path',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'navish-sender-'));try{const kp=generateX25519KeyPair();fs.writeFileSync(d+'/dev',JSON.stringify({protocol:PROTOCOL,controllerId:'test',publicKeyPem:kp.publicKeyPem}));fs.writeFileSync(d+'/key','preserve original');const env={...process.env,HOME:d,NAVISH_CONFIG_DIR:d+'/config',NAVISH_STATE_DIR:d+'/state',NAVISH_DATA_DIR:d+'/data'};const r=spawnSync(cmd,[...pre,'prepare','--device-json',d+'/dev','--target','local','--tool','get_config','--out',d+'/out','--response-key',d+'/key'],{env,encoding:'utf8'});assert.notEqual(r.status,0);assert.equal(fs.readFileSync(d+'/key','utf8'),'preserve original');assert.equal(fs.existsSync(d+'/out'),false)}finally{fs.rmSync(d,{recursive:true,force:true})}});
}
test('Python decrypter opens a real Node encrypted response',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'navish-interop-'));try{const kp=generateX25519KeyPair();const meta={protocol:PROTOCOL,controllerId:'test',commandId:'interop',createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+60000).toISOString()};const q=encryptRequest({devicePublicKeyPem:kp.publicKeyPem,payload:{x:1},meta});const r=encryptResult({responsePublicKeyPem:q.envelope.crypto.ephemeralPublicKeyPem,payload:{state:'completed',answer:42},meta});fs.writeFileSync(d+'/result',JSON.stringify(r));fs.writeFileSync(d+'/key',q.responsePrivateKeyPem,{mode:0o600});const out=spawnSync('python3',[PY,'decrypt','--result',d+'/result','--response-key',d+'/key'],{encoding:'utf8'});assert.equal(out.status,0,out.stderr);assert.deepEqual(JSON.parse(out.stdout),{state:'completed',answer:42})}finally{fs.rmSync(d,{recursive:true,force:true})}});
